import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Generate a list of images from the public/images directory
 * This script runs at build time to automatically discover available images
 */
function generateImageList() {
  const imagesDir = path.join(__dirname, '../public/images');
  const outputFile = path.join(__dirname, '../src/utils/imageList.js');
  
  try {
    // Check if images directory exists
    if (!fs.existsSync(imagesDir)) {
      console.log('Images directory does not exist, creating empty list');
      fs.writeFileSync(outputFile, 'export const HOME_IMAGES = [];\n');
      return;
    }
    
    // Read all files in the images directory
    const files = fs.readdirSync(imagesDir);
    
    // Filter for image files
    const imageExtensions = ['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg'];
    const imageFiles = files.filter(file => {
      const ext = path.extname(file).toLowerCase();
      return imageExtensions.includes(ext);
    });
    
    // Generate paths relative to public directory
    const imagePaths = imageFiles.map(file => `/images/${file}`);
    
    // Generate the JavaScript file content
    const content = `// Auto-generated list of home page background images
// This file is generated by scripts/generateImageList.js
// Do not edit manually - add images to public/images/ directory instead

export const HOME_IMAGES = ${JSON.stringify(imagePaths, null, 2)};
`;
    
    // Write the generated file
    fs.writeFileSync(outputFile, content);
    
    console.log(`Generated image list with ${imagePaths.length} images:`, imagePaths);
    
  } catch (error) {
    console.error('Error generating image list:', error);
    // Write empty list as fallback
    fs.writeFileSync(outputFile, 'export const HOME_IMAGES = [];\n');
  }
}

// Run the script
generateImageList();
