// Auto-generated list of home page background images
// This file is generated by scripts/generateImageList.js
// Do not edit manually - add images to public/images/ directory instead

export const HOME_IMAGES = [
  "/images/IMG_0489.png",
  "/images/IMG_3195.png",
  "/images/IMG_6429.png",
  "/images/IMG_6479.png",
  "/images/IMG_7671.png",
  "/images/IMG_8083.png",
  "/images/IMG_9395.png",
  "/images/IMG_9450.png",
  "/images/IMG_9519.png",
  "/images/bwca2_home.png",
  "/images/bwca_home.png"
];
