// Auto-generated list of home page background images
// This file is generated by scripts/generateImageList.js
// Do not edit manually - add images to public/images/ directory instead

export const HOME_IMAGES = [
  "/images/bwca2_home.png",
  "/images/bwca_home.png"
];
