// Auto-generated list of optimized images
// This file is generated by the image optimization plugin
// Do not edit manually

export const OPTIMIZED_IMAGES = [
  {
    "original": "/images/IMG_0424.png",
    "webp": "/images/IMG_0424.webp",
    "lqip": "/images/IMG_0424.lqip.webp"
  },
  {
    "original": "/images/IMG_0468.png",
    "webp": "/images/IMG_0468.webp",
    "lqip": "/images/IMG_0468.lqip.webp"
  },
  {
    "original": "/images/IMG_0477.png",
    "webp": "/images/IMG_0477.webp",
    "lqip": "/images/IMG_0477.lqip.webp"
  },
  {
    "original": "/images/IMG_0489.png",
    "webp": "/images/IMG_0489.webp",
    "lqip": "/images/IMG_0489.lqip.webp"
  },
  {
    "original": "/images/IMG_0507.png",
    "webp": "/images/IMG_0507.webp",
    "lqip": "/images/IMG_0507.lqip.webp"
  },
  {
    "original": "/images/IMG_3195.png",
    "webp": "/images/IMG_3195.webp",
    "lqip": "/images/IMG_3195.lqip.webp"
  },
  {
    "original": "/images/IMG_6429.png",
    "webp": "/images/IMG_6429.webp",
    "lqip": "/images/IMG_6429.lqip.webp"
  },
  {
    "original": "/images/IMG_6479.png",
    "webp": "/images/IMG_6479.webp",
    "lqip": "/images/IMG_6479.lqip.webp"
  },
  {
    "original": "/images/IMG_7671.png",
    "webp": "/images/IMG_7671.webp",
    "lqip": "/images/IMG_7671.lqip.webp"
  },
  {
    "original": "/images/IMG_8083.png",
    "webp": "/images/IMG_8083.webp",
    "lqip": "/images/IMG_8083.lqip.webp"
  },
  {
    "original": "/images/IMG_8429.png",
    "webp": "/images/IMG_8429.webp",
    "lqip": "/images/IMG_8429.lqip.webp"
  },
  {
    "original": "/images/IMG_8618.png",
    "webp": "/images/IMG_8618.webp",
    "lqip": "/images/IMG_8618.lqip.webp"
  },
  {
    "original": "/images/IMG_8699.png",
    "webp": "/images/IMG_8699.webp",
    "lqip": "/images/IMG_8699.lqip.webp"
  },
  {
    "original": "/images/IMG_8736.png",
    "webp": "/images/IMG_8736.webp",
    "lqip": "/images/IMG_8736.lqip.webp"
  },
  {
    "original": "/images/IMG_9212.png",
    "webp": "/images/IMG_9212.webp",
    "lqip": "/images/IMG_9212.lqip.webp"
  },
  {
    "original": "/images/IMG_9330.png",
    "webp": "/images/IMG_9330.webp",
    "lqip": "/images/IMG_9330.lqip.webp"
  },
  {
    "original": "/images/IMG_9348.png",
    "webp": "/images/IMG_9348.webp",
    "lqip": "/images/IMG_9348.lqip.webp"
  },
  {
    "original": "/images/IMG_9395.png",
    "webp": "/images/IMG_9395.webp",
    "lqip": "/images/IMG_9395.lqip.webp"
  },
  {
    "original": "/images/IMG_9450.png",
    "webp": "/images/IMG_9450.webp",
    "lqip": "/images/IMG_9450.lqip.webp"
  },
  {
    "original": "/images/IMG_9479.png",
    "webp": "/images/IMG_9479.webp",
    "lqip": "/images/IMG_9479.lqip.webp"
  },
  {
    "original": "/images/IMG_9519.png",
    "webp": "/images/IMG_9519.webp",
    "lqip": "/images/IMG_9519.lqip.webp"
  },
  {
    "original": "/images/IMG_9882.png",
    "webp": "/images/IMG_9882.webp",
    "lqip": "/images/IMG_9882.lqip.webp"
  }
];

// Helper function to get image data by original path
export const getImageData = (originalPath) => {
  return OPTIMIZED_IMAGES.find(img => img.original === originalPath);
};

// Helper function to get all WebP image paths
export const getWebPImages = () => {
  return OPTIMIZED_IMAGES.map(img => img.webp);
};

// Helper function to get all LQIP image paths
export const getLQIPImages = () => {
  return OPTIMIZED_IMAGES.map(img => img.lqip).filter(Boolean);
};
